#!/bin/sh
# Builds build/Slipstream Menubar.app from the Swift package and signs it ad hoc.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
CONFIGURATION=${CONFIGURATION:-release}
APP="$ROOT/build/Slipstream Menubar.app"

swift build --package-path "$ROOT" -c "$CONFIGURATION" --arch arm64
BINARY=$(swift build --package-path "$ROOT" -c "$CONFIGURATION" --arch arm64 --show-bin-path)/SlipstreamMenubar

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BINARY" "$APP/Contents/MacOS/SlipstreamMenubar"
cp "$ROOT/Resources/Info.plist" "$APP/Contents/Info.plist"
# Generated by scripts/make-icon.swift from the bolt; committed so builds need no drawing.
cp "$ROOT/Resources/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
# MARKETING_VERSION (e.g. 26.10.0, from a release tag) sets the version users see;
# the build number is the commit.
BUILD=$(git -C "$ROOT" describe --always --dirty 2>/dev/null || echo dev)
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$APP/Contents/Info.plist"
if [ -n "${MARKETING_VERSION:-}" ]; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $MARKETING_VERSION" "$APP/Contents/Info.plist"
fi
codesign --force --sign - --options runtime "$APP"
echo "$APP"
